### PR TITLE
Implementating FEN Strings to initialize a virtual chess position.

### PR DESCRIPTION
**Pull request by CodeWithBhuvan**
Updated the board.h and board.c files accordingly. Please have a look..

### CODE REVIEW

**Comment by CodeWithBhuvan** [comment]
Could you please have a look at my pull request?

**Review by roh1th-s — CHANGES_REQUESTED** [review]
You need to include 

```c
#include <stdio.h>
#include <ctype.h>
```

in board.c

also place the static functions at the end of the file before the chess_board_from_fen function so it's defined before it is used

**Comment by CodeWithBhuvan** [comment]
Okay, I have done the changes. Is it correct now?

**Comment by roh1th-s** [comment]
> Okay, I have done the changes. Is it correct now?

@CodeWithBhuvan I should've been more clear, apologies. What I meant was you need to move the static functions(that were initially at the end of the file) above the chess_board_from_fen() fn. Or better yet just define the functions at the top of the file and keep the implementation wherever (like it was done for update_castling_rights)

**Comment by CodeWithBhuvan** [comment]
Oh now I get it! I feel so dumb for doing that.

**Comment by roh1th-s** [comment]
> Oh now I get it! I feel so dumb for doing that. 
@CodeWithBhuvan happens to the best of us. here's your bounty

**Comment by roh1th-s** [comment]
!bounty 400

**Pull request merged**
